#!/bin/bash
# One way conversion of "_alt" texture variants into their defaults.
#
# Script for the 'magenta' alternates.
# 

cp alternate_textures/texture_alts/magenta/baked_clay_magenta_alt.png minetest_game_mods/bakedclay/baked_clay_magenta.png
cp alternate_textures/texture_alts/magenta/baked_clay_terracotta_magenta_alt.png minetest_game_mods/bakedclay/baked_clay_terracotta_magenta.png
cp alternate_textures/texture_alts/magenta/dye_magenta_alt.png textures/dye_mcl_dye/dye_magenta.png
cp alternate_textures/texture_alts/magenta/hardenedclay_magenta_alt.png mcimport_mods/hardenedclay/hardenedclay_magenta.png
cp alternate_textures/texture_alts/magenta/hardened_clay_stained_magenta_alt.png textures/mcl_colorblocks/hardened_clay_stained_magenta.png
cp alternate_textures/texture_alts/magenta/jeija_lightstone_magenta_off_alt.png mcimport_mods/mesecons/mesecons_lightstone/jeija_lightstone_magenta_off.png
cp alternate_textures/texture_alts/magenta/jeija_lightstone_magenta_on_alt.png mcimport_mods/mesecons/mesecons_lightstone/jeija_lightstone_magenta_on.png
cp alternate_textures/texture_alts/magenta/magenta_mc_firework_star_alt.png textures/custom_edition/new_fireworks/magenta_mc_firework_star.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_magenta_alt.png textures/beds_mcl_beds/mcl_beds_bed_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_magenta_inv_alt.png textures/beds_mcl_beds/mcl_beds_bed_magenta_inv.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_side_bottom_magenta_alt.png textures/beds_mcl_beds/mcl_beds_bed_side_bottom_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_side_bottom_r_magenta_alt.png textures/beds_mcl_beds/mcl_beds_bed_side_bottom_r_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_side_top_r_magenta_alt.png textures/beds_mcl_beds/mcl_beds_bed_side_top_r_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_top_bottom_magenta_alt.png textures/beds_mcl_beds/mcl_beds_bed_top_bottom_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_beds_bed_top_top_magenta_alt.png textures/beds_mcl_beds/mcl_beds_bed_top_top_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_candles_item_magenta_alt.png textures/mcl_candles/mcl_candles_item_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_chests_magenta_shulker_box_top_alt.png textures/mcl_chests/mcl_chests_magenta_shulker_box_top.png
cp alternate_textures/texture_alts/magenta/mcl_colorblocks_concrete_magenta_alt.png textures/mcl_colorblocks/mcl_colorblocks_concrete_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_colorblocks_concrete_powder_magenta_alt.png textures/mcl_colorblocks/mcl_colorblocks_concrete_powder_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_colorblocks_glazed_terracotta_magenta_alt.png textures/mcl_colorblocks/mcl_colorblocks_glazed_terracotta_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_core_glass_magenta_alt.png textures/default_mcl_core/glass/mcl_core_glass_magenta.png
cp alternate_textures/texture_alts/magenta/mcl_dye_magenta_alt.png textures/dye_mcl_dye/mcl_dye_magenta.png
cp alternate_textures/texture_alts/magenta/mobs_mc_llama_decor_magenta_alt.png textures/mobs_mc/llama/mobs_mc_llama_decor_magenta.png
cp alternate_textures/texture_alts/magenta/mobs_mc_shulker_magenta_alt.png textures/mobs_mc/shulker/mobs_mc_shulker_magenta.png
cp alternate_textures/texture_alts/magenta/wool_magenta_alt.png textures/wool_mcl_wool/wool_magenta.png



