#!/bin/bash
# One way conversion of "_alt" texture variants into their defaults.
#
# Script for the large amount of diamond retextures.
# 
#


cp alternate_textures/texture_alts/diamonds/3d_armor_boots_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_boots_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_boots_diamond_preview_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_boots_diamond_preview.png
cp alternate_textures/texture_alts/diamonds/3d_armor_chestplate_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_chestplate_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_chestplate_diamond_preview_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_chestplate_diamond_preview.png
cp alternate_textures/texture_alts/diamonds/3d_armor_helmet_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_helmet_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_helmet_diamond_preview_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_helmet_diamond_preview.png
cp alternate_textures/texture_alts/diamonds/3d_armor_inv_boots_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_inv_boots_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_inv_chestplate_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_inv_chestplate_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_inv_helmet_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_inv_helmet_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_inv_leggings_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_inv_leggings_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_leggings_diamond_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_leggings_diamond.png
cp alternate_textures/texture_alts/diamonds/3d_armor_leggings_diamond_preview_alt.png minetest_game_mods/3d_armor/3d_armor/3d_armor_leggings_diamond_preview.png

cp alternate_textures/texture_alts/diamonds/shields_inv_shield_diamond_alt.png minetest_game_mods/3d_armor/shields/shields_inv_shield_diamond.png
cp alternate_textures/texture_alts/diamonds/shields_shield_diamond_alt.png minetest_game_mods/3d_armor/shields/shields_shield_diamond.png
cp alternate_textures/texture_alts/diamonds/shields_shield_diamond_preview_alt.png minetest_game_mods/3d_armor/shields/shields_shield_diamond_preview.png


cp alternate_textures/texture_alts/diamonds/bolt_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/bolt_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/coast_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/coast_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/dune_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/dune_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/eye_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/eye_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/flow_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/flow_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/host_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/host_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/raiser_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/raiser_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/rib_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/rib_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/sentry_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/sentry_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/shaper_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/shaper_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/silence_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/silence_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/snout_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/snout_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/spire_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/spire_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/tide_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/tide_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/vex_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/vex_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/ward_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/ward_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/wayfinder_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/wayfinder_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/wild_armor_trim_smithing_template_alt.png textures/mcl_armor/mcl_armor_trims/wild_armor_trim_smithing_template.png 
cp alternate_textures/texture_alts/diamonds/mcl_armor_trim_netherite_upgrade_alt.png textures/mcl_armor/mcl_armor_trims/mcl_armor_trim_netherite_upgrade.png


cp alternate_textures/texture_alts/diamonds/default_diamond_alt.png textures/default_mcl_core/minerals_ores/default_diamond.png
cp alternate_textures/texture_alts/diamonds/default_diamond_block_alt.png textures/default_mcl_core/minerals_ores/default_diamond_block.png
cp alternate_textures/texture_alts/diamonds/default_mineral_diamond_alt.png textures/default_mcl_core/minerals_ores/default_mineral_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_core_diamond_ore_alt.png textures/default_mcl_core/minerals_ores/mcl_core_diamond_ore.png

cp alternate_textures/texture_alts/diamonds/mcl_deepslate_diamond_ore_alt.png textures/mcl_deepslate/mcl_deepslate_diamond_ore.png 


cp alternate_textures/texture_alts/diamonds/default_tool_diamondaxe_alt.png textures/default_mcl_core/tools/default_tool_diamondaxe.png
cp alternate_textures/texture_alts/diamonds/default_tool_diamondpick_alt.png textures/default_mcl_core/tools/default_tool_diamondpick.png
cp alternate_textures/texture_alts/diamonds/default_tool_diamondshovel_alt.png textures/default_mcl_core/tools/default_tool_diamondshovel.png
cp alternate_textures/texture_alts/diamonds/default_tool_diamondsword_alt.png textures/default_mcl_core/tools/default_tool_diamondsword.png

cp alternate_textures/texture_alts/diamonds/farming_tool_diamondhoe_alt.png textures/farming_mcl_farming/farming_tool_diamondhoe.png

cp alternate_textures/texture_alts/diamonds/fs_tools_hammer_diamond_alt.png skyfactory/fromscratch/fs_tools_hammer_diamond.png


cp alternate_textures/texture_alts/diamonds/mcl_armor_boots_diamond_alt.png textures/mcl_armor/mcl_armor_boots_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_boots_diamond_preview_alt.png textures/mcl_armor/mcl_armor_boots_diamond_preview.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_chestplate_diamond_alt.png textures/mcl_armor/mcl_armor_chestplate_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_chestplate_diamond_preview_alt.png textures/mcl_armor/mcl_armor_chestplate_diamond_preview.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_helmet_diamond_alt.png textures/mcl_armor/mcl_armor_helmet_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_helmet_diamond_preview_alt.png textures/mcl_armor/mcl_armor_helmet_diamond_preview.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_inv_boots_diamond_alt.png textures/mcl_armor/mcl_armor_inv_boots_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_inv_chestplate_diamond_alt.png textures/mcl_armor/mcl_armor_inv_chestplate_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_inv_helmet_diamond_alt.png textures/mcl_armor/mcl_armor_inv_helmet_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_inv_leggings_diamond_alt.png textures/mcl_armor/mcl_armor_inv_leggings_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_leggings_diamond_alt.png textures/mcl_armor/mcl_armor_leggings_diamond.png
cp alternate_textures/texture_alts/diamonds/mcl_armor_leggings_diamond_preview_alt.png textures/mcl_armor/mcl_armor_leggings_diamond_preview.png

cp alternate_textures/texture_alts/diamonds/mcl_mobitems_diamond_horse_armor_alt.png textures/mcl_mobitems/mcl_mobitems_diamond_horse_armor.png
cp alternate_textures/texture_alts/diamonds/mcl_mobitems_horse_armor_diamond_alt.png textures/mcl_mobitems/mcl_mobitems_horse_armor_diamond.png

cp alternate_textures/texture_alts/diamonds/mobs_mc_diamond_horse_armor_alt.png textures/mobs_mc/horse/mobs_mc_diamond_horse_armor.png
cp alternate_textures/texture_alts/diamonds/mobs_mc_horse_armor_diamond_alt.png textures/mobs_mc/horse/mobs_mc_horse_armor_diamond.png


cp alternate_textures/texture_alts/diamonds/mcl_enchanting_table_side_alt.png textures/mcl_enchanting/mcl_enchanting_table_side.png
cp alternate_textures/texture_alts/diamonds/mcl_enchanting_table_top_alt.png textures/mcl_enchanting/mcl_enchanting_table_top.png

cp alternate_textures/texture_alts/diamonds/xdecor_enchantment_side_alt.png mcimport_mods/xdecor/xdecor_enchantment_side.png
cp alternate_textures/texture_alts/diamonds/xdecor_enchantment_top_alt.png mcimport_mods/xdecor/xdecor_enchantment_top.png
