#!/bin/bash
# One way conversion of "_alt" texture variants into their defaults.
#
# Script for the large amount of 'basic_materials' retextures.
# 
#



cp alternate_textures/texture_alts/basic_materials/basic_materials_aluminum_bar_alt.png mcimport_mods/basic_materials/basic_materials_aluminum_bar.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_aluminum_strip_alt.png mcimport_mods/basic_materials/basic_materials_aluminum_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_aluminum_wire_alt.png mcimport_mods/basic_materials/basic_materials_aluminum_wire.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_brass_block_alt.png mcimport_mods/basic_materials/basic_materials_brass_block.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_brass_ingot_alt.png mcimport_mods/basic_materials/basic_materials_brass_ingot.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_carbon_steel_bar_alt.png mcimport_mods/basic_materials/basic_materials_carbon_steel_bar.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_cement_block_alt.png mcimport_mods/basic_materials/basic_materials_cement_block.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_chain_brass_alt.png mcimport_mods/basic_materials/basic_materials_chain_brass.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_chain_brass_inv_alt.png mcimport_mods/basic_materials/basic_materials_chain_brass_inv.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_chainlink_brass_alt.png mcimport_mods/basic_materials/basic_materials_chainlink_brass.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_chainlink_steel_alt.png mcimport_mods/basic_materials/basic_materials_chainlink_steel.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_chain_steel_alt.png mcimport_mods/basic_materials/basic_materials_chain_steel.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_chain_steel_inv_alt.png mcimport_mods/basic_materials/basic_materials_chain_steel_inv.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_concrete_block_alt.png mcimport_mods/basic_materials/basic_materials_concrete_block.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_copper_strip_alt.png mcimport_mods/basic_materials/basic_materials_copper_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_copper_wire_alt.png mcimport_mods/basic_materials/basic_materials_copper_wire.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_empty_spool_alt.png mcimport_mods/basic_materials/basic_materials_empty_spool.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_energy_crystal_alt.png mcimport_mods/basic_materials/basic_materials_energy_crystal.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_gear_steel_alt.png mcimport_mods/basic_materials/basic_materials_gear_steel.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_gold_strip_alt.png mcimport_mods/basic_materials/basic_materials_gold_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_gold_wire_alt.png mcimport_mods/basic_materials/basic_materials_gold_wire.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_heating_element_alt.png mcimport_mods/basic_materials/basic_materials_heating_element.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_ic_alt.png mcimport_mods/basic_materials/basic_materials_ic.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_lead_strip_alt.png mcimport_mods/basic_materials/basic_materials_lead_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_motor_alt.png mcimport_mods/basic_materials/basic_materials_motor.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_oil_extract_alt.png mcimport_mods/basic_materials/basic_materials_oil_extract.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_padlock_alt.png mcimport_mods/basic_materials/basic_materials_padlock.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_paraffin_alt.png mcimport_mods/basic_materials/basic_materials_paraffin.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_plastic_sheet_alt.png mcimport_mods/basic_materials/basic_materials_plastic_sheet.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_plastic_strip_alt.png mcimport_mods/basic_materials/basic_materials_plastic_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_silicon_alt.png mcimport_mods/basic_materials/basic_materials_silicon.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_silver_wire_alt.png mcimport_mods/basic_materials/basic_materials_silver_wire.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_stainless_steel_bar_alt.png mcimport_mods/basic_materials/basic_materials_stainless_steel_bar.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_stainless_steel_strip_alt.png mcimport_mods/basic_materials/basic_materials_stainless_steel_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_stainless_steel_wire_alt.png mcimport_mods/basic_materials/basic_materials_stainless_steel_wire.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_steel_bar_alt.png mcimport_mods/basic_materials/basic_materials_steel_bar.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_steel_strip_alt.png mcimport_mods/basic_materials/basic_materials_steel_strip.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_steel_wire_alt.png mcimport_mods/basic_materials/basic_materials_steel_wire.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_terracotta_base_alt.png mcimport_mods/basic_materials/basic_materials_terracotta_base.png
cp alternate_textures/texture_alts/basic_materials/basic_materials_wet_cement_alt.png mcimport_mods/basic_materials/basic_materials_wet_cement.png

